version: '3.9'

services:
  redis_storage:
    image: redis
    restart: always
    command: redis-server --save 5 1 --loglevel warning
    ports:
      - 6390:6379
    volumes:
      - $PWD/redis_storage:/data
