version: '3.9'

services:
  http-nest-todo-caching:
    build:
      context: .
    ports:
      - 3071:3070
    volumes:
      - ./:/home/node/app
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3070

      - MONGODB_PORT=27017
      - MONGODB_USERNAME=serhii
      - MONGODB_PASSWORD=serhii_pass
      - MONGODB_HOST=mongo_db
      - MONGODB_NAME=nestjs-http-todo
      - MONGODB_AUTH_MECHANISM=DEFAULT
      - MONGODB_AUTH_SOURCE=admin

      - CACHE_TTL=10
      - REDIS_CACHE_HOST=redis_cache
      - REDIS_CACHE_PORT=6379

    depends_on:
      - mongo_db
    command: sh -c './entr.dev.sh'
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - $PWD/mongo_datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: serhii
      MONGO_INITDB_ROOT_PASSWORD: serhii_pass
      MONGO_INITDB_DATABASE: nestjs-http-todo
  redis_cache:
    image: redis:latest
    restart: always
    volumes:
      - $PWD/redis_data:/usr/local/etc/redis
